---
title: "Decoding EEG During Action Observation, Motor Imagery, & Motor Execution"
author: "Evan Woods"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.width = 6)
knitr::opts_chunk$set(fig.asp = 0.618)
knitr::opts_chunk$set(out.width = "70%")
knitr::opts_chunk$set(fig.align = "center")
knitr::opts_chunk$set(
  comment = ""
)
```

```{r message=FALSE, include=FALSE}
if(!require("MASS")) install.packages("MASS")
if(!require("ISLR2")) install.packages("ISLR2")
if(!require("tidyverse")) install.packages("tidyverse")
if(!require("HH")) install.packages("HH") # VIF
if(!require("e1071")) install.packages("e1071") # naiveBayes
if(!require("class")) install.packages("class") # knn
if(!require("formulaic")) install.packages("formulaic")
if(!require("caTools")) install.packages("caTools")
if(!require("caret")) install.packages("caret")
if(!require("boot")) install.packages("boot")
if(!require("leaps")) install.packages("leaps") # regsubsets
if(!require("glmnet")) install.packages("glmnet") # Ridge and Lasso Regression
if(!require("pls")) install.packages("pls") # Partial Least Squares & Principal Component Regression
if(!require("splines")) install.packages("splines")
if(!require("gam")) install.packages("gam")
if(!require("akima")) install.packages("akima")
if(!require("tree")) install.packages("tree") # Classification and Regression Trees
if(!require("randomForest")) install.packages("randomForest")
if(!require("gbm")) install.packages("gbm") # Boosted Trees
if(!require("BART")) install.packages("BART")
if(!require("reticulate")) install.packages("reticulate") # Use python objects in R
if(!require("ROCR")) install.packages("ROCR")
if(!require("keras")) install.packages("keras") # Install keras for deep learning
if(!require("jpeg")) install.packages("jpeg")
if(!require("imager")) install.packages("imager")
if(!require("tensorflow")) install.packages("te")

library(tensorflow)
library(imager)
library(keras)
reticulate::use_condaenv(condaenv = "r-tensorflow")
library(ROCR)
library(reticulate)
library(BART)
library(gbm)
library(randomForest)
library(tree)
library(akima)
library(gam)
library(splines)
library(glmnet)
library(pls)
library(leaps)
library(formulaic)
library(class)
library(e1071)
library(HH)
library(MASS)
library(ISLR2)
library(tidyverse)
library(caTools)
library(caret)
library(boot)
library(jpeg)
```

```{r output=FALSE, results = 'hide', message=FALSE}
# keras::install_keras(method = "conda", python_version = "3.10")
```

```{r include=FALSE}
# Check tensorflow GPU configuration
# tf$config$list_physical_devices("GPU")
# R.version$arch
# tf$constant("Hello Tensorflow!")
```

```{r include=FALSE}
custom_darkblue = "#1A0875"
custom_lightblue = "#34ABEB"
custom_red = "#a60808"
```

```{r include=FALSE}
f_print <- function(string){
  cat(str_wrap(string = string, width = 80, indent = 0, exdent = 0, whitespace_only = TRUE))
}
```



## Gathering data from IEEE Paper Decoding AO vs. MI vs. ME

### Imports
```{r}
# Imports
import("sklearn")
import("mne")
import("numpy", as = "np")

base_dir <- 'pysitstand/'

eeg_py <- str_c(base_dir, 'eeg.py')
eeg_preprocessing_py <- str_c(base_dir, 'eeg_preprocessing.py')
emg_preprocessing_py <- str_c(base_dir, 'emg_preprocessing.py')
info_py <- str_c(base_dir, 'info.py')
model_py <- str_c(base_dir, 'model.py')
rASR_m <- str_c(base_dir, 'rASR.m')
utils_py <- str_c(base_dir, 'utils.py')

source_python(eeg_py) 
source_python(eeg_preprocessing_py)
source_python(emg_preprocessing_py)
source_python(info_py)
source_python(model_py)
# source_python(rASR_m)
source_python(utils_py)

  
# csv_file_name_EEG = 'S01_EEG_1'
# S01_EEG_1 = EEG(csv_file_name_EEG)
```

### Function Definitions

### Body

```{python}
    # filter params
    new_sfreq = 250 # for downsampling before applying ica
    notch = {'f0': 50}
    bandpass = {'lowcut': 1, 'highcut': 40, 'order': filter_order}
    ica = {'new_sfreq': new_sfreq, 'save_name': None, 'threshold': 2}

    # it will perform preprocessing from this order
    filter_method = {'notch_filter': notch, 
                    'butter_bandpass_filter': bandpass,
                    'ica': ica}
                    
processed_data = apply_eeg_preprocessing(subject_name='S01', session='mi', task='sit', filter_method = filter_method)
```


```{python}
# filter params
new_sfreq = 250 # for downsampling before applying ica
notch = {'f0': 50}
bandpass = {'lowcut': 1, 'highcut': 40, 'order': filter_order}
ica = {'new_sfreq': new_sfreq, 'save_name': None, 'threshold': 2}
# it will perform preprocessing from this order
filter_method = {'butter_bandpass_filter': bandpass, 'ica': ica}
                
session = 'mi'
task = 'sit'

subject_name='S01'
```


```{python}
subject_path = DATASET_PATH+'/'+subject_name+'_EEG/'
sfreq = 1200
new_sfreq = sfreq
```


```{python}
if filter_method is not None:
    for key in filter_method.keys():
        if key=='ica' or key=='rASR':
            new_sfreq = filter_method[key]['new_sfreq'] if filter_method[key]['new_sfreq'] is not None else sfreq
# subject_path = 'pysitstand/raw_data/'+subject_name+'_EEG/'
runs, trials, channels, datapoint = 3, 5, 11, 15*new_sfreq
processed_data = np.zeros((runs, trials, channels, datapoint)) # 3 runs, 5 trials, 11 eeg channels, 14 sec*250 Hz
```

```{python}
# processed_data
```


```{python}
# for each run. Normally, each subject has 3 runs
for i in range(runs):
    p_name = subject_path + subject_name+ '_EEG_' + str(i+1)+'.csv'
    eeg = EEG(p_name, 1200)
    raw_array = eeg.read_CSV()
    if session == 'me': # ME 
        arr_sit, arr_stand = eeg.collect_data_allphase(3, raw_array)
        if task == 'sit':
            del arr_stand
            data = arr_sit
        elif task == 'stand':
            del arr_sit
            data = arr_stand
    elif session == 'mi': # MI 
        if task == 'sit':
            data = eeg.collect_data_allphase(7, raw_array)
        elif task == 'stand':
            data = eeg.collect_data_allphase(6, raw_array)
# preprocessing method
    data.shape
    print(filter_method.items())
    for key, value in filter_method.items():
        if key == 'butter_bandpass_filter':
            print(sfreq)
            data = peform_butter_bandpass_filter(data, value['lowcut'], value['highcut'], sfreq, value['order'])
            print('butter_bandpass_filter:', value)
        elif key == 'notch_filter':
            data = peform_notch_filter(data, value['f0'], sfreq, 25)
            print('notch_filter:', value)
        elif key == 'highpass_filter':
            data = peform_highpass_filter(data, value['highcut'], sfreq, value['order'])
            print('highpass_filter:', value)
        elif key == 'ica':
            print("ica")
            data = perform_ica(data, sfreq, value['new_sfreq'], value['save_name'], value['threshold'])
            sfreq = value['new_sfreq'] # after resample
            print('ica:', value)
        elif key == 'rASR':
            data = rASR(data, sfreq, value['new_sfreq'])
            print('rASR', value)
    tmp = data
# preprocessing method      
    # tmp = preprocessing(data=data, filter_method=filter_method, sfreq=sfreq)
    print("tmp:")
    print(tmp)
    processed_data[i] = tmp[:,:channels,:] # drop EOG channels
```

```{python}
processed_data = processed_data.reshape(-1, channels, datapoint) # reshape 4D to 3D
```


```{python}
processed_data
```

```{python}
subject_name='S01'
```


```{python}
subject_path = DATASET_PATH+'/'+subject_name+'_EEG/'
```


```{python}
subject_path
```



```{python}
sfreq = 1200
    new_sfreq = sfreq
    if filter_method is not None:
        for key in filter_method.keys():
            if key=='ica' or key=='rASR':
                new_sfreq = filter_method[key]['new_sfreq'] if filter_method[key]['new_sfreq'] is not None else sfreq
    # subject_path = 'pysitstand/raw_data/'+subject_name+'_EEG/'
    runs, trials, channels, datapoint = 3, 5, 11, 15*new_sfreq
    processed_data = np.zeros((runs, trials, channels, datapoint)) # 3 runs, 5 trials, 11 eeg channels, 14 sec*250 Hz
```


```{python}
subject_path
```


```{python}
# for each run. Normally, each subject has 3 runs
    for i in range(runs):
        p_name = subject_path + subject_name+ '_EEG_' + str(i+1)+'.csv'
        eeg = EEG(p_name, 1200)
        raw_array = eeg.read_CSV()
        if session == 'me': # ME 
            arr_sit, arr_stand = eeg.collect_data_allphase(3, raw_array)
            if task == 'sit':
                del arr_stand
                data = arr_sit
            elif task == 'stand':
                del arr_sit
                data = arr_stand
        elif session == 'mi': # MI 
            if task == 'sit':
                data = eeg.collect_data_allphase(7, raw_array)
            elif task == 'stand':
                data = eeg.collect_data_allphase(6, raw_array)

        tmp = preprocessing(data=data, filter_method=filter_method, sfreq=sfreq)
        processed_data[i] = tmp[:,:channels,:] # drop EOG channels

    processed_data = processed_data.reshape(-1, channels, datapoint) # reshape 4D to 3D
```

```{python}
proces
```



```{python}
apply_eeg_preprocessing('S01')
```


```{python}
# Create S01_EEG_1 handler
csv_file_name = './pysitstand/raw_data/S01_EEG/S01_EEG_1.csv'
S01_EEG_1_p = EEG(csv_file_name)
```

```{python}
# Create Scenario & Phase Structure
create_scenario_phase_data_structure(S01_EEG_1_p)
```


```{python}
# Reading Raw Data
S01_EEG_1_p.raw_data = S01_EEG_1_p.read_CSV()
S01_EEG_1_p.raw_data
```

```{python}
# collecting all scenarios
collect_all_scenarios(S01_EEG_1_p)
```





