---
title: "Chapter2"
author: "Evan Woods"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# ISLR2
if(!require("ISLR2")) install.packages("ISLR2")
```



# Section 2.3.1: Basic Commands
```{r}
# Concatonation:
x <- c(1, 3, 2, 5)
x
```

```{r}
# Saving a concatonation:
x = c(1, 6, 2)
x

y = c(1, 4, 3)
```

```{r}
# Add x and y:
length(x)

length(y) 

x + y
```

```{r}
# List all objects:
ls()
```

```{r}
# Delete objects:
rm(x, y)
```

```{r}
# Remove all objects at once:
rm(list = ls())
```

```{r}
# Creating a matrix:
x <- matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2)
x
```


```{r}
# Populate a matrix in the order of rows:
x <- matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE)
x
```

```{r}
# Return the square-root of each element of a vector or matrix:
sqrt(x)
```

```{r}
# Raise each element to the power of 2.
x^2
```

```{r}
# Generate a random normal vector:
x <- rnorm(50)
y <- x + rnorm(n = 50, mean = 50, sd = .1)
cor(x, y) # Compute the correlation between x & y
```
  
```{r}
# Reproduce the exact same set of random numbers:
set.seed(1303)
rnorm(50)
```
  
```{r}
# Compute the mean, variance, and standard deviation of a vector of numbers:
set.seed(3)
y <- rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
```
# Section 2.3.2: Graphics   
```{r}
x <- rnorm(100)
y <- rnorm(100)

plot(x, y)
plot(x, y, xlab = "This is the x-axis",
     ylab = "This is the y-axis", 
     main = "Plot of X vs Y")
```
  
```{r}
# Save a plot
pdf("Figure.pdf")
plot(x, y, col = "green")
dev.off()
```
  
```{r}
# Create a sequence of 10 numbers that are equally spaced between 0 and 1.
x <- seq(0, 1, length = 10)
x

# Create a sequence of 10 numbers from 1 to 10.
x <- seq(1, 10)
x

# Create a sequence of 50 evenly spaced numbers from -pi to pi
x <- seq(-pi, pi, length = 50)
x

```
  
  
```{r}
# Create a contour plot
y <- x
z <- outer(x, y, function(x, y) cos(y) / (1 + x^2))
contour(x, y, z)
contour(x, y, z, nlevels = 45, add = T)
za <- (z - t(z)) / 2
contour(x, y, za, nlevels = 2)
```
  
```{r}
# Create a heatmap:
image(x, y, z)
```
  
```{r}
# Create a three-dimensional plot:
persp(x, y, za)
persp(x, y, za, theta = 30)
persp(x, y, za, theta = 30, phi = 20)
persp(x, y, za, theta = 30, phi = 70)
persp(x, y, za, theta = 30, phi = 40)
```
# Section 2.3.3: Indexing Data
```{r}
# Create a matrix:
A <- matrix(1:16, nrow = 4, ncol = 4)
A
```
  
```{r}
# Address the 2nd row, 3rd column in matrix A:
A[2, 3]
```

```{r}
# Select multiple columns from matrix A by providing vectors as the indices:
A[c(1, 3), c(2, 4)]
A[1:3, 2:4]
A[1:2,]
A[, 1:2]
A[1,]
```

```{r}
# Keep all rows or columns except those indicated by the index:
A[-c(1, 3), ]
A[-c(1, 3), -c(1, 3, 4)]
```
```{r}
# Output the dimensions of a matrix:
dim(A)
```

# Section 2.3.4: Loading Data
```{r}
Auto <- read.table("Auto.data")
View(Auto)
head(Auto)
```

```{r}
Auto <- read.table("Auto.data", header = TRUE, na.strings = "?", stringsAsFactors = TRUE)
View(Auto)
```

```{r}
dim(Auto)
```

```{r}
# Remove missing rows:
Auto <- na.omit(Auto)
dim(Auto)
```

```{r}
Auto
names(Auto)
rm(Auto)
```

```{r}
# Loading ISLR2 to use the appropriate data:
library(ISLR2)
Auto <- ISLR2::Auto
```


```{r}
# Attaching variables:
plot(Auto$cylinders, Auto$mpg)
attach(Auto)
plot(cylinders, mpg)
```

```{r}
# Identify points using the R-Console:
# Type the following into the R-Console before clicking on any point in the interactive window & pressing 'escape':
plot(horsepower, mpg)
identify(horsepower, mpg, name)
```


```{r}
# Summarise the variables in the dataset "Auto":
summary(Auto)
```
```{r}

```


